USE PRACTICE

CREATE TABLE AVGTOP(COMMISSION1 FLOAT NOT NULL);
INSERT INTO AVGTOP(SELECT TOP 3 COMMISSION 
FROM AGENTS 
ORDER BY COMMISSION DESC
SELECT AVG(COMMISSION1) AS AVERAGEOFTOP3AGENTS FROM AVGTOP;
SELECT * FROM AVGTOP